package com.example.servivet.utils

object  PreferenceEntity {
    const val IS_LOGIN:String = "isLogin"
    const val NOTIFY_STATUS:String = "notification_Status"
    const val FROM_DATE: String="from_date"
    const val TOKEN: String="token"
    const val DEVICE_TOKEN: String="device_token"
    const val LOCATION: String="location"
    const val LOCATION_INFO: String="location_info"
    const val TYPE:String="type"
    const val STEPS_ID:String="steps_id"
    const val IS_RESET_PASSWORD:String="isResetPassword"
    var date = "selectedDate"
    const val VERIFY_DATA="verify_data"
    const val USER_PROFILE="user_profile"
    const val CATEGORY="category"
    const val USER_DETAILS="userDetails"
    const val MASTER_DATA="master_data"
    const val SAVE_ADDRESS="saveAddress"
    const val NOTIFICATION_DATA="notification_data"
    const val LOCATION_ADDRESS_INFO="location_address_info"
    const val LANGUAGE="language"
    const val POSITION="position"
}